# Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.

num = int(input('digite um numero para ver a taboada: '))
print('='* 15)
print('{} x {:2} é = {}'.format(num, 1, num*1))
print('{} x {:2} é = {}'.format(num, 2, num*2))
print('{} x {:2} é = {}'.format(num, 3, num*3))
print('{} x {:2} é = {}'.format(num, 4, num*4))
print('{} x {:2} é = {}'.format(num, 5, num*5))
print('{} x {:2} é = {}'.format(num, 6, num*6))
print('{} x {:2} é = {}'.format(num, 7, num*7))
print('{} x {:2} é = {}'.format(num, 8, num*8))
print('{} x {:2} é = {}'.format(num, 9, num*9))
print('{} x {:2} é = {}'.format(num, 10, num*10))
print('_' * 15)
